add postinstall script that downloads usb.ids and oui.ids

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -17,9 +17,43 @@ set -e
 # for details, see http://www.debian.org/doc/debian-policy/ or
 # the debian-policy package
 
+USBIDS=/usr/share/omphalos/usb.ids
+OUIIDS=/usr/share/omphalos/ieee-oui.txt
+
+OUT="`which get-oui 2> /dev/null`" || true
+WGET="`which wget 2> /dev/null`" || true
+ICONV="`which iconv 2> /dev/null`" || true
+
+tmp="`mktemp`"
+
+exithandle () {
+        trap "" EXIT
+        if [ -n "$tmp" ] ; then
+                rm -vf "$tmp" || true
+        fi
+}
+
+trap exithandle EXIT SIGINT SIGHUP
+
 
 case "$1" in
     configure)
+	if [ -n "$WGET" ] ; then
+		echo "Couldn't find wget; not updating USB IDs." >&2
+	elif [ -n "$ICONV" ] ; then
+		echo "Couldn't find iconv; not updating USB IDs." >&2
+	else
+		"$WGET" http://www.linux-usb.org/usb.ids -O "$tmp"
+		"$ICONV" -f iso-8859-1 -t utf-8 -o $USBIDS "$tmp"
+	fi
+	if [ -n "$OUI" ] ; then
+		echo "Couldn't find get-out; not updating OUI IDs." >&2
+	elif [ -n "$ICONV" ] ; then
+		echo "Couldn't find iconv; not updating OUI IDs." >&2
+	else
+		"$OUI" -v -f "$tmp"
+		"$ICONV" -f iso-8859-1 -t utf-8 -o "$OUIIDS" "$tmp"
+	fi
     ;;
 
     abort-upgrade|abort-remove|abort-deconfigure)
@@ -30,6 +64,9 @@ case "$1" in
         exit 1
     ;;
 esac
+
+rm "$tmp"
+tmp=""
 
 # dh_installdeb will replace this with shell code automatically
 # generated by other debhelper scripts.
