if setcap fails, fall back to setuid

diff --git a/tools/addcaps b/tools/addcaps
--- a/tools/addcaps
+++ b/tools/addcaps
@@ -13,7 +13,11 @@ usage () { usageerr >&2 ; return 1 ; }
 
 if SETCAP="`which setcap`" ; then
 	for i in "$@" ; do
-		"$SETCAP" "= cap_net_admin,cap_net_raw=ep" "$i"
+		if ! "$SETCAP" "= cap_net_admin,cap_net_raw=ep" "$i" ; then
+			echo "The 'setcap' binary failed, using setuid..." >&2
+			chown root:root "$i"
+			chmod +s "$i"
+		fi
 	done
 else
 	echo "Couldn't find the 'setcap' binary, using setuid..." >&2
